name: Check, build and run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check
    - name: make
      run: make
    - name: run
      run: ./push_swap "2 1 4"
