name: Norminette

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install apt deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc clang libpq-dev libbsd-dev libncurses-dev valgrind python3-dev python3-venv python3-wheel python3-testresources

    - run: echo "norminette" >> requirements.txt

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install norminette
      shell: bash
      run: |
        pip install --upgrade pip setuptools
        pip install -r requirements.txt

    - name: Make check - norminette
      run: make check
