name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone libf
      run: git submodule add https://github.com/unkn0wn107/libft

    - name: Test
      run: make test
